EMAIL_USER="velvet-genius.32@icloud.com"
EMAIL_PASS="nbuj-jhjp-zijm-bjsp"
FROM_NAME="KV Production â€“ Glass Line"

TO_EMAILS="ragavan.ramachandran@kvcustomwd.com, ning.ma@kvcustomwd.com"
CC_EMAILS="alok.kulkarni@kvcustomwd.com, clyde.orbanski@kvcustomwd.com"

ADMIN_PIN="2613"